---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
- type: heading
  label: Globals
- type: document
  path: src\_data\menu.json
  label: menu
- type: document
  path: src\_data\author.json
  label: Author
upload_dir: src/posts/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
